service: my-serverless-project

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get
