name: Build..

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js for the build (example with version 18)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build script
      - name: Build project
        run: npm run build
